version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Zipping build files..."
      - zip -r build.zip build
      - echo "Uploading to S3..."
      - aws s3 cp build.zip s3://hmcs-host-app/build.zip
artifacts:
  files:
    - build.zip